### PR TITLE
Fix the error when file size exceeds maxBytes

### PR DESCRIPTION
**Pull request by andyhu**
See #5

### CODE REVIEW

**Comment by andyhu** [comment]
Hi @mikermcneil @sgress454 what's the status of this one?

**Comment by cwolters** [comment]
Could you please fix the upload issues. It's a blocker in my project.

**Comment by mikermcneil** [comment]
working on it today

**Comment by mikermcneil** [comment]
@andyhu thank you!

**Comment by mikermcneil** [comment]
@cwolters @andyhu can you guys try out skipper@0.5.4 and skipper-disk@0.5.4?

**Comment by cwolters** [comment]
@mikermcneil I tried today and could not crash the process. For it looks okay. Will still have an eye on it!

**Pull request merged**
